version: '3'

services:
  storage-mongodb:
    container_name: "storage-mongodb"
    build: ./services/storage-mongodb
    ports:
      - 27017:27017
    restart: always
  api-python:
    container_name: "api-python"
    build: ./projects/api-python
    volumes: 
      - ./projects/api-python:/usr/src/app
    environment:
      - DB_HOST=storage-mongodb
      - DB_PORT=27017
      - DB_NAME=project-systat
    links:
      - storage-mongodb
    ports:
      - 5000:80
