version: '3'

services:
  storage-mysql:
    container_name: "storage-mysql"
    build: ./services/storage-mysql
    ports:
      - 27017:27017
    restart: always
    env_file: ./services/storage-mysql/db.env
  storage-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api-python:
    container_name: "api-python"
    build: ./projects/api-python
    volumes: 
      - ./projects/api-python:/usr/src/app
    env_file: ./services/api-python/api.env
    links:
      - storage-mongodb
    ports:
      - 5000:80
